export const LOGIN_USER = '[AUTH] LOGIN_USER';
export const LOGIN_USER_SUCCESS = '[AUTH] LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = '[AUTH] LOGIN_USER_FAIL';

export const SIGNUP_USER = '[AUTH] SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = '[AUTH] SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAIL = '[AUTH] SIGNUP_USER_FAIL';

export const FEED_ORDERS = '[FEED] GET_FEED_ORDERS';
export const FEED_ORDERS_SUCCESS = '[FEED] GET_FEED_ORDERS-SUCCESS';
export const FEED_ORDERS_FAIL = '[FEED] GET_FEED_ORDERS_FAIL';
